### ISSUE TITLE
Home Assistant Integration

### ISSUE THREAD

**Issue by jffz** [ssenart/PyGazpar#1]
The readme says that this project exists for an homeassistant integrationbut i cant find the said module sources.
Do you mind to upload even if it is still wip ?
I might be interested in helping you in this project.

**Comment by ssenart** [comment]
Hi jffz,It is available in home-assistant project only in my github, in gazpar dedicated branch.You can find the corresponding component files in subdirectory:/homeassistant/components/gazparYou have to deploy it as a custom component: copy the files inside the folder:<config_dir>/custom_components/gazparAnd add the configuration to your config file :sensor:- platform: gazpar  username: !secret gazpar.username  password: !secret gazpar.password  webdriver: /config/drivers/geckodriver  tmpdir: /tmp  scan_interval: 01:00:00i'm using it since several month and it works fine.I'm glad you have interests in this.The reason I did not push it yet in the main branch is the dependency with the geckodriver. I have read somewhere that HA team does not like that, but I should ask to be sure.Tell me whether you have some issues with it, and don't hesite to report bugs and ideas to make it better. Also, your contribution is welcome.ThanksStéphane 
-------- Message d'origine --------De : jffz <notifications@github.com> Date : 09/02/2020  02:27  (GMT+01:00) À : ssenart/PyGazpar <PyGazpar@noreply.github.com> Cc : Subscribed <subscribed@noreply.github.com> Objet : [ssenart/PyGazpar] Home Assistant Integration (#1) The readme says that this project exists for an homeassistant integrationbut i cant find the said module sources.
Do you mind to upload even if it is still wip ?
I might be interested in helping you in this project.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ssenart/PyGazpar/issues/1?email_source=notifications\u0026email_token=AI2MR62QM7KRWRTDME7GBMDRB5LYFA5CNFSM4KR6J342YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IMBBHMQ",
"url": "https://github.com/ssenart/PyGazpar/issues/1?email_source=notifications\u0026email_token=AI2MR62QM7KRWRTDME7GBMDRB5LYFA5CNFSM4KR6J342YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IMBBHMQ",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by jffz** [comment]
Thanks for your answer, I will try it out soon.
Isn't it possible to use BS4 or something lighter to parse gazpar website ?

**Comment by ssenart** [comment]
I looked at BS and Scrapy long time ago, but Grdf site has too much javascript. As far as i understood, BS and Scrapy works fine for basic Html. But with ajax based site, they may be not usable.If I'm wrong. I would be happy to simplify and not using selenium.Stéphane 
-------- Message d'origine --------De : jffz <notifications@github.com> Date : 09/02/2020  09:55  (GMT+01:00) À : ssenart/PyGazpar <PyGazpar@noreply.github.com> Cc : ssenart <stephane.senart@gmail.com>, Comment <comment@noreply.github.com> Objet : Re: [ssenart/PyGazpar] Home Assistant Integration (#1) Thanks for your answer, I will try it out soon.
Isn't it possible to use BS4 or something lighter to parse gazpar website ?

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ssenart/PyGazpar/issues/1?email_source=notifications\u0026email_token=AI2MR66KMF7KF2SE6M4KC43RB7AI5A5CNFSM4KR6J342YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELGGPNY#issuecomment-583821239",
"url": "https://github.com/ssenart/PyGazpar/issues/1?email_source=notifications\u0026email_token=AI2MR66KMF7KF2SE6M4KC43RB7AI5A5CNFSM4KR6J342YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELGGPNY#issuecomment-583821239",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by max5962** [comment]
Awesome idea !
Maybe create an hacs version of your integration could promote your awesome works !
I found your project just by accident :-)

**Comment by max5962** [comment]
I can't get it working ...

I copy filed in custom_component : 
```
[....] /custom_components$ ls -ltr gazpar/
total 20
-rwxrwxrwx 1 XX 28 févr. 12 13:49 __init__.py
-rwxrwxrwx 1 XX  221 févr. 12 13:49 manifest.json
-rwxrwxrwx 1 XX 8001 févr. 12 13:50 sensor.py
drwxrwxrwx 2 root    root    4096 févr. 12 13:55 __pycache__
```

I configured the service :+1: 

```
- platform: gazpar
  username: XXXXXXXXXXXXXX
  password: XXXXXXXXXXXXXXXXX
  webdriver: /config/drivers/geckodriver
  tmpdir: /tmp
  scan_interval: 01:00:00
```

I download the driver : 

```
ls -ltr drivers/
total 6848
-rwxrwxrwx 1 XX 7008696 oct.  12 12:19 geckodriver
```

What's missing ? :)

thanks

**Comment by max5962** [comment]
why did not use : https://github.com/empierre/domoticz_gaspar/blob/master/gaspar.py ?

**Comment by ssenart** [comment]
Service configuration has to be in 'sensor' section like that :

```
sensor:
  - platform: gazpar
    username: XXXXXXXXXXXXXX
    password: XXXXXXXXXXXXXXXXX
    webdriver: /config/drivers/geckodriver
    tmpdir: /tmp
    scan_interval: 01:00:00
```
Also, be sure geckodriver binary is compatible with your platform.

In case of issues, you can increase the log verbosity and check messages in home-assistant.log:

```
logger:
  default: warning
  logs:
    custom_components.gazpar: debug
```
Tell me if it helps !

**Comment by ssenart** [comment]
Indeed project at  https://github.com/empierre/domoticz_gaspar/blob/master/gaspar.py is very interesting: It does not work with Selenium and does not depend on geckodriver.
However, I don't know how the payload were created (probably by sniffing the web interaction between the server and the browser). If GRDF site changes, i won't be able to maintain with such source code. For me, Selenium is easier to use and adjust in case of site changes.

**Comment by max5962** [comment]
> Indeed project at https://github.com/empierre/domoticz_gaspar/blob/master/gaspar.py is very interesting: It does not work with Selenium and does not depend on geckodriver.
> However, I don't know how the payload were created (probably by sniffing the web interaction between the server and the browser). If GRDF site changes, i won't be able to maintain with such source code. For me, Selenium is easier to use and adjust in case of site changes.

Yes seems to need gecko AND Firefox installed not ?
In docker environment seems not really possible isn't ?

**Comment by max5962** [comment]
> Service configuration has to be in 'sensor' section like that :
> 
> ```
> sensor:
>   - platform: gazpar
>     username: XXXXXXXXXXXXXX
>     password: XXXXXXXXXXXXXXXXX
>     webdriver: /config/drivers/geckodriver
>     tmpdir: /tmp
>     scan_interval: 01:00:00
> ```
> 
> Also, be sure geckodriver binary is compatible with your platform.
> 
> In case of issues, you can increase the log verbosity and check messages in home-assistant.log:
> 
> ```
> logger:
>   default: warning
>   logs:
>     custom_components.gazpar: debug
> ```
> 
> Tell me if it helps !

Yes it's configured in sensor section :-)
And yes the binary is compatible with the host / container.
Does I also need Firefox to be installed ?
Or gecko is enough?

Thanks.

**Comment by ssenart** [comment]
Yes, you're right, Firefox has to be installed as well.

Sorry, I have forgotten this detail. :-)

**Comment by max5962** [comment]
For the moment I could add a script that load at startup and install dependencies.
Can you send the command please ?;-)

**Comment by ssenart** [comment]
HomeAssistant docker image is using Alpine Linux distribution.

Package manager apk is described here : https://wiki.alpinelinux.org/wiki/Alpine_Linux_package_management

1. Command to update the index:
```
# apk update                                                                                                                                                                 
```       
2. Command to install firefox:
```
# apk add firefox-esr                                                                                                                                                        
```

**Comment by jffz** [comment]
just looked at epierre's project and looks like this approach might be a lot less resources consuming than running selenium.

I might give it a look to adapt it for HA

**Comment by ssenart** [comment]
Ok jffz, could you keep me informed of your progress. I'm interested on how the payload object inside his code is built. My concern is being able to adjust this code easily in case of GRDF site change.

**Comment by max5962** [comment]
>  apk add firefox-esr

I'm sorry but i'm still having the same issue :(
which version of gecko did you download ?

**Comment by ssenart** [comment]
I'm using:
- home-assistant 0.100.2 embedded in the official docker image.
- firefox 60.9.0 installed manually in the same container with the apk command (see above).
- geckodriver 0.24.0.

Does the geckodriver file access right is ok from inside the container ?

I have :

```
bash-5.0# ls -l                                                                                                                                                                       
total 8548                                                                                                                                                                                                                                                                                               
-rwxrwx---    1 1001     users      8724590 Jan 28  2019 geckodriver   
```
And, running the geckodriver command (from inside the container):

```
bash-5.0# ./geckodriver --version                                                                                                                                                     
geckodriver 0.24.0 ( 2019-01-28)                                                                                                                                                      
                                                                                                                                                                                      
The source code of this program is available from                                                                                                                                     
testing/geckodriver in https://hg.mozilla.org/mozilla-central.                                                                                                                        
                                                                                                                                                                                      
This program is subject to the terms of the Mozilla Public License 2.0.                                                                                                               
You can obtain a copy of the license at https://mozilla.org/MPL/2.0/.   
```
And with firefox command:

```
bash-5.0# firefox --version                                                                                                                                                           
Mozilla Firefox 60.9.0   
```

**Comment by max5962** [comment]
> I'm using:
> 
> * home-assistant 0.100.2 embedded in the official docker image.
> * firefox 60.9.0 installed manually in the same container with the apk command (see above).
> * geckodriver 0.24.0.
> 
> Does the geckodriver file access right is ok from inside the container ?
> 
> I have :
> 
> ```
> bash-5.0# ls -l                                                                                                                                                                       
> total 8548                                                                                                                                                                                                                                                                                               
> -rwxrwx---    1 1001     users      8724590 Jan 28  2019 geckodriver   
> ```
> 
> And, running the geckodriver command (from inside the container):
> 
> ```
> bash-5.0# ./geckodriver --version                                                                                                                                                     
> geckodriver 0.24.0 ( 2019-01-28)                                                                                                                                                      
>                                                                                                                                                                                       
> The source code of this program is available from                                                                                                                                     
> testing/geckodriver in https://hg.mozilla.org/mozilla-central.                                                                                                                        
>                                                                                                                                                                                       
> This program is subject to the terms of the Mozilla Public License 2.0.                                                                                                               
> You can obtain a copy of the license at https://mozilla.org/MPL/2.0/.   
> ```
> 
> And with firefox command:
> 
> ```
> bash-5.0# firefox --version                                                                                                                                                           
> Mozilla Firefox 60.9.0   
> ```

Gecko is not runnable :( 
Even add 777 right !

**Comment by ssenart** [comment]
On which kind of processor do you run your host ? Intel, ARM, ... ?

For example, on Raspberry (ARM), you have to get geckodriver for Raspberry.

**Comment by max5962** [comment]
> On which kind of processor do you run your host ? Intel, ARM, ... ?
> 
> For example, on Raspberry (ARM), you have to get geckodriver for Raspberry.

It's an i7 :-)

**Comment by max5962** [comment]
> just looked at empierre's project and looks like this approach might be a lot less resources consuming than running selenium.
> 
> I might give it a look to adapt it for HA

I created the skeleton 
https://github.com/max5962/gazpar-homeAssistant
You can contribute and change everything you need.

**Comment by ssenart** [comment]
No more activities here...

**Comment by frtz13** [comment]
if anybody is interested: I made a Home Assistant integration as a "command line sensor". no need to install additional components. see: https://github.com/frtz13/homeassistant_gazpar_cl_sensor
